language: java
before_install: 
  - sudo apt-get install -y ant-contrib
  - sudo ln -s /usr/share/java/ant-contrib.jar /usr/share/ant/lib/
  - ant deps
install: "ant -v jar"
script: "./runTests.py --single --verbose --show_diff"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
